### ISSUE TITLE
Hotkeys for input proxy/output proxy/subgraph

### ISSUE THREAD

**Issue by fthr** [vizorvr/vizor-create#28]
These are the three most common plugins that are inserted into graphs, so they should have hotkeys for faster workflows.

Suggestions: 
I for input proxy
O for output proxy
G for subgraph

Use case:
Hit G and the "Name new graph" dialog is opened. User puts in a name and the subgraph is created.
Hit I and a new input proxy with the default name (input-n) is created in the graph.
Hit O and a new output proxy with the default name is created in the graph.

**Comment by kschzt** [comment]
I suggest turning this into a hot key manager *without* a configurable ui now, so that we could add a layer that emits events when hotkeys / gestures are seen. The related actions could then listen to their events, eg. ("user action", "add plugin", "input proxy"). We could also add hotkeys 1-8 to "my presets" so that you could map your favorite custom presets into the number keys. For example.

**Comment by kschzt** [comment]
done
